### ISSUE TITLE
Metadatabase inconsistency if update fails.

### ISSUE THREAD

**Issue by ethack** [activecm/rita-blacklist#10]
If rita-blacklist fails during a blacklist update, it still writes to the metadatabase causing rita to think that the blacklist is up to date.  This leads to false negatives due to the blacklist not being populated correctly.

This has happened to me twice.  Once where the update appeared to hang for far too long so I killed it.  Running again did not cause another update and there were no blacklist entries.  The second time there was a segfault that I believe was caused by a network issue (my firewall blocked the update attempt).

```
2017/06/17 22:58:27 Updating blacklist source:  myip-ms . This may take a few minutes...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1356ce6]

goroutine 32 [running]:
github.com/ocmdev/rita-blacklist/hostlist.(*MyIpMs).downloadFile(0x18069c8, 0x158151b, 0x14, 0x0, 0x0)
	$GOPATH/src/github.com/ocmdev/rita-blacklist/hostlist/myipms.go:49 +0xb6
github.com/ocmdev/rita-blacklist/hostlist.(*MyIpMs).UpdateList(0x18069c8, 0xc4203b6d20, 0x0, 0x0)
	$GOPATH/src/github.com/ocmdev/rita-blacklist/hostlist/myipms.go:146 +0x58
github.com/ocmdev/rita-blacklist.(*BlackList).Init.func1(0xc4201af170, 0xc4203b6d20, 0xc4201af9c0)
	$GOPATH/src/github.com/ocmdev/rita-blacklist/blacklist.go:58 +0x3d
created by github.com/ocmdev/rita-blacklist.(*BlackList).Init
	$GOPATH/src/github.com/ocmdev/rita-blacklist/blacklist.go:60 +0x474
```

I'd suggest that the blacklist loader detects if no new entries are added (e.g. if the database is uninitialized, has 0 entries, or is the same size as before the update) and to not modify the metadatabase.

**Comment by Zalgo2462** [comment]
I am currently working on a replacement for rita-blacklist which will take care of these problems by design. https://github.com/Zalgo2462/rita-blacklist2
