### ISSUE TITLE
Find more blacklist databases

### ISSUE THREAD

**Issue by ethack** [activecm/rita-blacklist#2]
Enhance the current blacklisting module by finding more quality sources.
Ideas:
- Lists in this readme described as malware or spam: https://github.com/notracking/hosts-blocklists/
- Lists in this readme described as malware or spam: https://github.com/StevenBlack/hosts/blob/master/readme.md
- https://mirror1.malwaredomains.com/files/justdomains
- https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
- https://github.com/A3sal0n/FalconGate/blob/master/intel-sources.md

Criteria
- Looking for lists containing either domains, IPs, or URLs
- Only looking for malicious lists, not ads, tracking, etc.

Ideally, create a new file for each list using hostlist/myipms.go as a template.

**Comment by carrohan** [comment]
I'll plan on starting with http://www.malwaredomainlist.com/hostslist/hosts.txt  (listed in the first linked readme)

**Comment by carrohan** [comment]
After digging around it looks like everything blocked on the zeus tracker is also in the malware domain list, so that one should be covered as well

**Comment by ethack** [comment]
This could be a good one to look into.  It doesn't provide info in a list format and we might be limited on queries but I'll leave it here for future reference.

* https://threatpost.com/malware-hunter-crawls-internet-looking-for-rat-c2s/125360/
* https://malware-hunter.shodan.io/

**Comment by ethack** [comment]
@Zalgo2462 once told me some blacklists are circulated via DNS zone transfer.  I'd be interested to look at these sources too but haven't run across any yet.
